Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  AutoCorrect: true
  EnforcedStyle: always
Metrics/BlockLength:
  Max: 120
Layout/IndentationStyle:
  Enabled: true
  IndentationWidth: 2
  EnforcedStyle: spaces
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods
